### PR TITLE
Improve main CMake file

### PR DESCRIPTION
**Pull request by miketsukerman**
Rename target date_interface to interface and tz to timezone.
Export targets date::interface and date::timezone from cmake.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Thanks for doing this.  But I'm going to be removing CMake support in the future due to my inability to maintain it.  I'm looking for volunteers to host CMake support on their own github site which I would gladly point to from my readme.

**Comment by warzon** [comment]
> Thanks for doing this. But I'm going to be removing CMake support in the future due to my inability to maintain it. I'm looking for volunteers to host CMake support on their own github site which I would gladly point to from my readme.

Can I ask what is the reason for removing cmake support?

**Comment by HowardHinnant** [comment]
I don't use it, nor understand it.  So I am unable to help maintain it, or even review quality PR's to improve it such as yours.

**Comment by miketsukerman** [comment]
Making a separate fork with cmake looks not very efficient. May I consider helping you in such cases? So you can leave cmake's in the original repository.

**Comment by HowardHinnant** [comment]
Ok, we'll try it!  You're in charge of reviewing all PR's involving CMakeLists.txt.   I've got to warn you, the pay is lousy. ;-)

**Pull request merged**
