### PR TITLE
cmake: date_interface as INTERFACE target, to enable automatic include_directory when using header-only date.h without tz

### PR DESCRIPTION
**Pull request by ajneu**
(for cases where just date.h, but not "tz.h and its lib" are needed)

We can now do this:

```cmake
cmake_minimum_required(VERSION 3.0.2)

project(go)

# -std=c++14
if (NOT    CMAKE_VERSION VERSION_LESS 3.1)
  set(CMAKE_CXX_STANDARD   14)
  set(CMAKE_CXX_EXTENSIONS OFF)
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
endif()

add_subdirectory(date) # working dir of Hinnant's date repo

add_executable(go main.cpp)
target_link_libraries(go date_interface)  # we link the date_interface !!!!!!!!!!!!!!!
```

The last line above is the important one! We use a socalled CMake [Interface "Library"](https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries) (which is not a real library).
Notice: we do **not** have to write
```cmake
include_directories(date/include)
```
We just attach our target `go` with interface `date_interface`, and get the correct include-dir automatically (for the header-only usage of `date/date.h`)

Here's some example cpp code, that uses just `#include "date/date.h"`, and not tz.
It completes the example.

```cpp
#include <iostream>
#include "date/date.h"

int main()
{
    using namespace std::chrono;
    using namespace date;
    std::cout << floor<days>(system_clock::now()) << std::endl;
    return 0;
}
```
We don't need to link it to tz, so we don't want the CMakeLists.txt to have
```cmake
target_link_libraries(go tz) 
```

### CODE REVIEW

**Comment by ajneu** [comment]
I did another commit, removing a `include_directories` which failed to list a directory.
Signature from [CMake Ref](https://cmake.org/cmake/help/latest/command/include_directories.html)
```cmake
include_directories([AFTER|BEFORE] [SYSTEM] dir1 [dir2 ...])
```

**Comment by ajneu** [comment]
This [line](https://github.com/HowardHinnant/date/blob/d3b8d4af8dd3430e1758176c0e2ea8b1e66217ea/CMakeLists.txt#L56)
```cmake
target_link_libraries( tz ${CMAKE_THREAD_LIBS_INIT} ${OPTIONAL_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT} )
```
seems fishy.
Surely we don't need to mention `${CMAKE_THREAD_LIBS_INIT}` twice?

**Comment by ajneu** [comment]
By the way:
If I do
```bash
git clone https://github.com/HowardHinnant/date.git
cd date

mkdir build
cd    build
cmake ..
make testit
```

I get the following **compile error**:
```make
[  4%] Building CXX object CMakeFiles/tz_test_pass_zoned_time_bin.dir/test/tz_test/zoned_time.pass.cpp.o
/home/albert/repo_wiesheu/date_test/src/date/test/tz_test/zoned_time.pass.cpp: In function ‘int main()’:
/home/albert/repo_wiesheu/date_test/src/date/test/tz_test/zoned_time.pass.cpp:135:9: error: static assertion failed
         static_assert(!is_constructible<zoned_seconds, sys_time<milliseconds>>{}, "");
         ^~~~~~~~~~~~~
/home/albert/repo_wiesheu/date_test/src/date/test/tz_test/zoned_time.pass.cpp:172:9: error: static assertion failed
         static_assert(!is_constructible<zoned_time<days>, zoned_seconds>{}, "");
         ^~~~~~~~~~~~~
CMakeFiles/tz_test_pass_zoned_time_bin.dir/build.make:62: recipe for target 'CMakeFiles/tz_test_pass_zoned_time_bin.dir/test/tz_test/zoned_time.pass.cpp.o' failed
make[3]: *** [CMakeFiles/tz_test_pass_zoned_time_bin.dir/test/tz_test/zoned_time.pass.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tz_test_pass_zoned_time_bin.dir/all' failed
make[2]: *** [CMakeFiles/tz_test_pass_zoned_time_bin.dir/all] Error 2
CMakeFiles/Makefile2:398: recipe for target 'CMakeFiles/testit.dir/rule' failed
make[1]: *** [CMakeFiles/testit.dir/rule] Error 2
Makefile:264: recipe for target 'testit' failed
make: *** [testit] Error 2
```

```bash
c++ --version
```
shows:
```
c++ (Debian 6.3.0-18) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ajneu** [comment]
PS: maybe using `date` as **interface** name is not specific enough. [Link](https://github.com/ajneu/date/blob/master/CMakeLists.txt#L67)
People using your date-files and cmake, in large projects may already have libraries called `date`.

So maby we should change `date` to `date_interface` in these lines:
[L67](https://github.com/ajneu/date/blob/master/CMakeLists.txt#L67)
[L70](https://github.com/ajneu/date/blob/master/CMakeLists.txt#L70)

Thoughts?

**Comment by ajneu** [comment]
> So maby we should change `date` to `date_interface` in these lines of the pull-request:
> [L67](https://github.com/ajneu/date/blob/master/CMakeLists.txt#L67)
> [L70](https://github.com/ajneu/date/blob/master/CMakeLists.txt#L70)

The example CMakeLists.txt from the top, would then change to this:

```cmake
cmake_minimum_required(VERSION 3.2)

project(go)

# -std=c++14
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_EXTENSIONS OFF)

add_subdirectory(date) # working dir of Hinnant's date repo

add_executable(go main.cpp)
target_link_libraries(go date_interface)  # we link the date interface !!!!!!!!!!!!!!!
```
with a **change in the last line**!

**Comment by ajneu** [comment]
Should we include cmake compilation examples, using cmake, that can be referenced from the top-level README?

e.g. this folder structure
```
demo
 `--------- demo_using_date_and_not_tz
 `--------- demo_using_tz
```

**Comment by beached** [comment]
Threads are needed on at least Linux

**Comment by ajneu** [comment]
> Threads are needed on at least Linux

I don't see `thread.h` in `date.h`

**Comment by ajneu** [comment]
I also propose changing
```cmake
option( BUILD_STATIC "Build a static version of library" ON )
```
to 
```cmake
option( BUILD_TZ_STATIC "Build a static version of library" ON )
```
[Link](https://github.com/HowardHinnant/date/blob/master/CMakeLists.txt#L11)

for when people use a working dir of the repo as a subdirectory of cmake, like this:

```cmake
cmake_minimum_required(VERSION 3.2)

project(go)

# -std=c++14
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_EXTENSIONS OFF)

add_subdirectory(date) # working dir of Hinnant's date repo

add_executable(go main.cpp)
target_link_libraries(go date_interface)  # we link the date interface !!!!!!!!!!!!!!!
```
so they can call cmake like this:
```bash
cmake -D BUILD_TZ_STATIC=ON ..
```

**Comment by HowardHinnant** [comment]
https://howardhinnant.github.io/date/tz.html#Installation documents that `-lpthread` is needed on linux.  All platforms use `std::call_once`.

**Comment by ajneu** [comment]
> https://howardhinnant.github.io/date/tz.html#Installation documents that -lpthread is needed on linux. All platforms use std::call_once for the tz database initialization.

Ah ok, the thread is needed for `tz`. 

But this pull-request, is about having automatic include_directories set, when using only the header-only `date.h` without `tz`.

So if you're using:
* header-only `date.h`, then do: 
 `target_link_libraries(my_target_name date_interface)`
* `tz`, then do: 
 `target_link_libraries(my_target_name tz)`
 Threads are already automatically linked for the tz lib.

**Comment by drrlvn** [comment]
I would remove the `print_option` stuff, I don't see why it's needed. You can always use cmake to check option values.

The rest seems OK to me, I think this PR should be accepted.

**Comment by HowardHinnant** [comment]
I _think_ I just merged this, but please double check for correctness.  It builds fine on macOS.

**Comment by ajneu** [comment]
Hi Mr. Hinnant,

yes you did merged it (so that r-darwish's changes [ref](https://github.com/HowardHinnant/date/commit/44c2515280372570a75b3af15fe6700fe618f9eb) are properly kept), and it looks fine. All good, as far as I can see.

.
.

Regarding drrlvn's comment (from [above](https://github.com/HowardHinnant/date/pull/261#issuecomment-352367773)), that he
> [...] would remove the print_option stuff, I don't see why it's needed.

Feel free to remove the `print_option` stuff from line [13](https://github.com/HowardHinnant/date/blob/447687870fe5f2a716b484463abd6f468e6fecb1/CMakeLists.txt#L13) to 22, if you think that it's annoying. I personally don't think it's annoying, that the cmake run now prints the following status information:
```bash
# date: USE_SYSTEM_TZ_DB OFF
# date: USE_TZ_DB_IN_DOT OFF
# date: BUILD_TZ_STATIC ON
```

**Comment by HowardHinnant** [comment]
Thanks for your contributions and review @ajneu .  I think due to merging on my part your date/master branch may not be sync'd with my master branch.  If you have a git remote for my date (say named HowardHinnant), try: `git fetch HowardHinnant` followed by `git reset --hard HowardHinnant/master` to sync back up.  But first save any outstanding edits you intend to keep.

Then I recommend starting with a new P/R if there are further modifications you would like to make.  Sorry if this seems overly bureaucratic.  I know just enough git to be dangerous, and am trying to stay away from git's dark corners.

**Comment by ajneu** [comment]
I understand your concerns.

I made a minor change that results in less cmake-variable pollution, by _marking_ certain "internally-used" (in function `print-option`) but unfortunately globally visible cmake-variables... _as advanced_.
See #271

**Pull request closed without merging**
