### PR TITLE
Allow disabling of testing

### PR DESCRIPTION
**Pull request by beached**
Setting ENABLE_TESTING=OFF will disable testing

### CODE REVIEW

**Comment by SlavSlavov** [comment]
When I tested my proposal I did the following (file attached as well) :
- used more specific option name like ENABLE_DATE_TESTING or something similar. Using ENABLE_TESTING is more general and might be used in other components as well.
- moved enable_testing just above add_custom_target testit and guarded everything from eneble_testing to the end.
[CMakeLists.txt](https://github.com/HowardHinnant/date/files/1610178/CMakeLists.txt)

**Comment by HowardHinnant** [comment]
@SlavSlavov Do you approve this P/R?  Or are you requesting modifications?  Thanks.

**Comment by SlavSlavov** [comment]
I would suggest to use the modifications I made. Thanks.

**Comment by beached** [comment]
I have no problem with ENABLE_DATE_TESTING as the flag, updated

**Comment by SlavSlavov** [comment]
Here is the output of "make testit" with your modifications:
```
[user@workstation date_build]$ make testit
[100%] Built target tz
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]

[100%] Built target testit
[user@workstation date_build]$ 
```
And with my modifications:
```
[user@workstation date_build]$ make testit
make: *** No rule to make target 'testit'.  Stop.
[user@workstation date_build]$ 
```

**Comment by HowardHinnant** [comment]
So what is the right move for this PR?  Looking for more advice, thanks.

**Comment by SlavSlavov** [comment]
I have provided a CMakeLists.txt file (attached in one of my comments) which I would like to be used. My understanding is that when testing is not enabled, the target "testit" should not be available at all. 
I am not sure if I can commit changes to this pull request so just use the file I attached.

**Comment by HowardHinnant** [comment]
Thanks @SlavSlavov But I don't have confidence that your recommended CMakeLists.txt is taking the latest CMakeLists.txt into account.  For example is it purposefully or accidentally reverting changes made in https://github.com/HowardHinnant/date/commit/637e5d80075c09de62db1282356dad56b1565754 ?

**Comment by SlavSlavov** [comment]
@HowardHinnant - sorry, this had to be a very simple change and I think it is going in the wrong direction. When I initially proposed it in #18, I proposed how to be done. When I added the file to this thread, the master branch was not yet updated. I'll post the steps to make the change here. All you need is to add an option which enables testing and at the end guards everything related to testing (not the contents of each function as the commits in this PR suggest). If you think this makes sense and can be done easily I would appreciate having it. If not just delete the PR.


Remove the line ```enable_testing( )``` which is at the beginning of the file

Add the following option at the end of your options list:
```
option( ENABLE_DATE_TESTING  "Enable unit tests" ON )
```

Add the following option at the end of your print options list
```
print_option( ENABLE_DATE_TESTING )
```

Add the following just before the line ```add_custom_target( testit COMMAND ${CMAKE_CTEST_COMMAND} )``` and indent everything to the end of the file

```
if ( ENABLE_DATE_TESTING )

    enable_testing( )
```

At the end of the file add ```endif( )``` 

Now everything related to testing is guarded and should look like this:


```
if ( ENABLE_DATE_TESTING )

    enable_testing( )

    add_custom_target( testit COMMAND ${CMAKE_CTEST_COMMAND} )

    ....

    endforeach( )
endif( )
```

**Comment by HowardHinnant** [comment]
@SlavSlavov @beached For your review:  https://github.com/HowardHinnant/date/pull/291

**Comment by HowardHinnant** [comment]
Addressed by https://github.com/HowardHinnant/date/commit/4ada98d247b5b68a061efdcf4b0a276b1e966e57

**Pull request closed without merging**
