### PR TITLE
iOS support

### PR DESCRIPTION
**Pull request by schmidt9**
Added support for iOS
For unpacking used https://github.com/nvh/NVHTarGzip

### CODE REVIEW

**Comment by HowardHinnant** [comment]
It looks to me like `wordexp` is available on iOS:
https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/wordexp.3.html

What issues did you have when running `wordexp`?

**Comment by HowardHinnant** [comment]
I'm guessing that the problem you had was in specifying the correct paths using C++.  That you need to use Apple's Core Foundation Library (or whatever its called) to get the correct path.  If that's correct, I'd like to merge this.

One remaining issue:  Your copyright is too strict for this open source project.  Can you use the MIT license, such as in tz.cpp?

**Comment by schmidt9** [comment]
The link you have given refers to os x, not ios, although "ios" word in link text may be confusing. XCode gives me error "'wordexp' is unavailable: not available on iOS". I'll correct copyright.

**Comment by schmidt9** [comment]
The same for wordfree

**Comment by HowardHinnant** [comment]
If you're having git problems correcting the copyright, I can take care of that for you.  I just didn't want to do something like that without your permission.

**Comment by schmidt9** [comment]
It seems that there is no chance to get out only with c++. iOS does not allow to create folders and files in app's home directory, calling mkdir etc works on Simulator, but fails on real device. Core Foundation lets only read file system info, not write something. It is possible to change file extension with ObjC code (ios.mm) from mm to cpp to get rid of possible compiler complains, that's all.

**Comment by schmidt9** [comment]
It is related to db unpacking, if we move this part to app's ObjC code and leave in cpp file only db reading logic, then with Core Foundation it is possible.

**Comment by HowardHinnant** [comment]
What you have proposed above works, right?

**Comment by HowardHinnant** [comment]
Merged.

**Pull request closed without merging**
