### PR TITLE
error: ignoring return value of ‘char* strerror_r(int, char*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]

### PR DESCRIPTION
**Pull request by nvelozsavino**
when compiling for release (-O3 -DNDEBUG) and -Werror and -pedantic the compilation fails because return value of strerror_r is ignored, according to documentation (at least the GNU version of strerror_r) strerror_r returns a pointer to a string containing the error message. This may be either a pointer to a string that the function stores in buf, or a pointer to some (immutable) static string (in which case buf is unused).

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Needed to fix it like this: https://github.com/HowardHinnant/date/commit/6a31edcb3843d4cdfe34a9c0e7a3d871a1fe38c8 because gcc and POSIX differ on the return type.

**Comment by nvelozsavino** [comment]
That won't do it, I already tried it and it still complains for the same error, at least g++ 4.8.5

**Comment by HowardHinnant** [comment]
I'm attempting to reproduce this here: http://melpon.org/wandbox/permlink/vHqca27ft0HJYFaF

So far I'm not having much success.  If you could help me reproduce it, perhaps we could find a better solution together.  Thanks.

**Comment by nvelozsavino** [comment]
in the link you send me I couldn't reproduce it, however the same code in my server fail to compile, note that the version of the compilers are slighly different
```

GNU C++ (Ubuntu 4.8.5-2ubuntu1~14.04.1) version 4.8.5 (x86_64-linux-gnu)
	compiled by GNU C version 4.8.5, GMP version 5.1.3, MPFR version 3.1.3, MPC version 1.0.1
```
```
g++ test.cc -v -std=c++11 -Werror  -O3
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1) 
COLLECT_GCC_OPTIONS='-v' '-std=c++11' '-Werror' '-O3' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/4.8/cc1plus -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE test.cc -quiet -dumpbase test.cc -mtune=generic -march=x86-64 -auxbase test -O3 -Werror -std=c++11 -version -fstack-protector -Wformat -Wformat-security -o /tmp/cciEUDIt.s
GNU C++ (Ubuntu 4.8.5-2ubuntu1~14.04.1) version 4.8.5 (x86_64-linux-gnu)
	compiled by GNU C version 4.8.5, GMP version 5.1.3, MPFR version 3.1.3, MPC version 1.0.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/4.8"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.8
 /usr/include/x86_64-linux-gnu/c++/4.8
 /usr/include/c++/4.8/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++ (Ubuntu 4.8.5-2ubuntu1~14.04.1) version 4.8.5 (x86_64-linux-gnu)
	compiled by GNU C version 4.8.5, GMP version 5.1.3, MPFR version 3.1.3, MPC version 1.0.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 712b39604af3a9de5c666e46cb37bfc6
test.cc: In function ‘int main()’:
test.cc:11:31: error: ignoring return value of ‘char* strerror_r(int, char*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
     strerror_r(errno, buf, 30);
                               ^
cc1plus: all warnings being treated as errors

```

I'll test in another environment to check

**Comment by nvelozsavino** [comment]
With gcc 5.4.0 also reproducible in another Ubuntu x86_64 environment

```
g++ test/test.cpp -v -std=c++11 -pedantic "-Werror" "-O3"
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
COLLECT_GCC_OPTIONS='-v' '-std=c++11' '-Wpedantic' '-Werror' '-O3' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/cc1plus -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE test/test.cpp -quiet -dumpbase test.cpp -mtune=generic -march=x86-64 -auxbase test -O3 -Wpedantic -Werror -std=c++11 -version -fstack-protector-strong -Wformat -Wformat-security -o /tmp/cceIPjLS.s
GNU C++11 (Ubuntu 5.4.0-6ubuntu1~16.04.4) version 5.4.0 20160609 (x86_64-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/5"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/5
 /usr/include/x86_64-linux-gnu/c++/5
 /usr/include/c++/5/backward
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++11 (Ubuntu 5.4.0-6ubuntu1~16.04.4) version 5.4.0 20160609 (x86_64-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: c3fdb80f2154421ceaf9e22c85325a8d
test/test.cpp: In function ‘int main()’:
test/test.cpp:11:31: error: ignoring return value of ‘char* strerror_r(int, char*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
     strerror_r(errno, buf, 30);
                               ^
cc1plus: all warnings being treated as errors

```

**Comment by HowardHinnant** [comment]
Perhaps inserting a pragma?
````
#pragma GCC diagnostic ignored "-Werror=unused-result"
````
This would need to be protected with `defined(__GNUC__) && !defined(__clang__)`  (or something along those lines).

**Comment by HowardHinnant** [comment]
I'm theorizing that the diagnostic is so persistent because: `declared with attribute warn_unused_result [-Werror=unused-result]`.

**Comment by HowardHinnant** [comment]
Here's a demo and fix: http://melpon.org/wandbox/permlink/zlBOm3oucmlAuyrX

**Comment by HowardHinnant** [comment]
Does this work for you?  https://github.com/HowardHinnant/date/commit/3724013464479ebaf3b4e7d8c89d0c60fbe8d7ef

**Comment by HowardHinnant** [comment]
Does this work for you?  https://github.com/HowardHinnant/date/commit/098223cf6d7214ba49815e06babd20dbbe85a79e

**Comment by nvelozsavino** [comment]
yes, that worked

**Pull request closed without merging**
