### PR TITLE
Towards a CMake support

### PR DESCRIPTION
**Pull request by daixtrose**
This is the very first step in a series of minor changes to introduce CMake support.
You can see its usage in [this demo](https://github.com/daixtrose/test-cmake-for-howard-hinnant-date-lib)

@HowardHinnant Probably it makes sense to make this PR to another branch.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
I created a sibling directory and from there I did:
```
cmake ../date
```
That appeared to go well:
```
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/howardhinnant/Development/build_date
```
And then I did:
```
make
```
I can't tell that it does anything.  I'm not sure what I'm looking for.

**Comment by daixtrose** [comment]
That is by purpose. This is the **first step only** excluding tz completely, only exposing the date library headers. See [demo](https://github.com/daixtrose/test-cmake-for-howard-hinnant-date-lib) how to use it.

**Comment by HowardHinnant** [comment]
Ok, experimental cmake branch here:

https://github.com/HowardHinnant/date/tree/cmake

**Comment by daixtrose** [comment]
OK, I will redirect (aka resubmit) the PR to that branch.

**Comment by daixtrose** [comment]
Oh! Already happend. Closing this one.

**Pull request closed without merging**
