### PR TITLE
Create CMakeList.txt

### PR DESCRIPTION
**Pull request by beached**
This is an implementation of cmake config relating to #18

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Thanks for your work on this.  Not ignoring, just preoccupied with another P/R at the moment.  Might be a few days before I respond.

Feel free to keep pushing changes to this P/R as opposed to closing and reopening.  Github will update this P/R with each of your pushes to `patch-2`.

**Comment by beached** [comment]
Sorry about that, yeah I had an issue and normally would just do that.

**Comment by beached** [comment]
I think I got it worked out
you can set the variables USE_SYSTEM_TZ_DB if you do not want to download from iana
```
cmake -DUSE_SYSTEM_TZ_DB=ON ..
```
If you want to download the iana db to the . folder you can set USE_TZ_DB_IN_DOT
```
cmake -DUSE_TZ_DB_IN_DOT ..
```
To run tests
```
cmake ..
make testit
```
If you want a shared library, static is default turn off BUILD_STATIC
```
cmake -DBUILD_STATIC=OFF ..
```
Otherwise the normal way of defining USE_AUTOLOAD, REMOTE_API... can be defined

**Comment by HowardHinnant** [comment]
On macOS I get:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
```
I started to track it down and then realized that openssl isn't needed for this lib.

**Comment by beached** [comment]
Isn’t it needed for curl to do https?

**Comment by HowardHinnant** [comment]
I just link with `-lcurl`.  `curl` may need it, but at least on macOS that's a private implementation detail of `curl`.  I don't directly include or link against openssl.

**Comment by beached** [comment]
Fixed and tested it on Ubuntu.  I checked for a feature flag of sorts but the CURL_VERSION_STRING in CMake only has the version number(e.g. 7.5.5).  If I find a system with curl that does not have ssl support(not sure it exists) I could document the failure so that it is obvious what is wrong.

**Comment by HowardHinnant** [comment]
Merged: https://github.com/HowardHinnant/date/commit/f3741d68ff06f34a6bd71ea556fdc7257b7365c6

Thanks!

**Comment by SylvainCorlay** [comment]
Quick feedback on the new CMakeList (sorry I was on the road earlier)

- Using the module `GNUInstallDirs` defines a number of variables for installation directories, which is a bit cleaner than using `INSTALLATION_PREFIX / include`.
- This will make cmake install the binaries in the right folder (lib, lib64) depending on the environment.
- Besides, a `ProjectConfig.cmake` would be really useful for library authors interested in depending on `date`.

**Pull request closed without merging**
