### PR TITLE
Honor symbol visibility settings

### PR DESCRIPTION
**Pull request by rigtorp**
When I use date inside a dynamic library I don't want to export date functions as part of my API so I set default visibility to hidden. This change makes date build honor this setting.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Closing.  Thank you for this good suggestion.  I am in the process of ending cmake support for this library.  I encourage interested parties to host their own cmake files for this library, and I would be happy to link to such support in my README.md.

**Comment by rigtorp** [comment]
@miketsukerman Given the discussion in #486 can we reopen this PR for review?

**Comment by HowardHinnant** [comment]
Can you rebase it?  Thanks.

**Comment by HowardHinnant** [comment]
Assigned @miketsukerman

**Comment by miketsukerman** [comment]
@HowardHinnant will have a look

**Comment by rigtorp** [comment]
@miketsukerman Rebased

**Comment by miketsukerman** [comment]
@HowardHinnant @rigtorp I would ask you to wait if it's possible with that patch. Cause I want to add ci build for this repository. Otherwise, I'm can't be confident that new changes are not breaking anything.

**Comment by rigtorp** [comment]
@miketsukerman Sure. Do you need help with that? I created the C++ build matrix here which is quiet extensive https://github.com/real-logic/simple-binary-encoding/blob/master/.travis.yml.

**Comment by miketsukerman** [comment]
@rigtorp sure, I'm open for any help. Please have a look at my wip pr https://github.com/HowardHinnant/date/pull/489

**Comment by HowardHinnant** [comment]
@miketsukerman ping.

**Comment by HowardHinnant** [comment]
@qis Do you have an opinion on this PR?  Thanks.

**Comment by qis** [comment]
I have little experience with non-current CMake (usually on nightly), but it looks like this is a reference to https://cmake.org/cmake/help/v3.7/policy/CMP0063.html. Shouldn't it be `3.7` or `CMP0063`, then?

I'm surprised that

> target_link_libraries(my_dynamic_lib **PRIVATE** date::date date::tz)

is not honored unless this is set. If that's the case, then this change is a very good idea.

Just to be sure, this is an ELF issue, where your `.so` file also exports date/tz symbols even though you link "privately" to `tz.a` and use `date.h` functions, correct?

**Comment by rigtorp** [comment]
Yes, I set:
```
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
```
But these settings are ignored (with a CMake warning) for subprojects in older versions of CMake. Since date specify CMake 3.1 as required, CMake will use the old behavior even on newer versions of cmake.

I specify policy version 3.12 because that also gives support for LTO.

**Comment by qis** [comment]
Isn't LTO something that should be done in the toolchain file? Anyway, great fix!

**Comment by rigtorp** [comment]
@qis https://cmake.org/cmake/help/latest/variable/CMAKE_INTERPROCEDURAL_OPTIMIZATION.html#variable:CMAKE_INTERPROCEDURAL_OPTIMIZATION

Same story as with visibility, not honored for old CMake

**Pull request merged**
