### PR TITLE
Add a more generic approach to get UNIX download folder

### PR DESCRIPTION
**Pull request by coin-au-carre**
Download folder can differ (especially on non-english Linux distribution). 
The changes propose to stick with the download folder provided with the [xdg-user-dir](https://freedesktop.org/wiki/Software/xdg-user-dirs/) command which is available in most Linux distribution : 

- Add an exec_and_get_output function to grab the result of xdg-user-dir with popen
- Change get_download_folder() so that it uses the above function, verify whether the output is eligible. Result should always be a valid path. 
- Added copyright if this work can be useful

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Nice idea, but this adds an unacceptable expense to initialization for those platforms that do not have  xdg-user-dir installed (which is too many).

However this issue can hopefully be handled either at compile time by the `INSTALL` macro, or at runtime by the soon-to-be-documented `void set_install(const std::string& install)` function.

I've also updated tz.cpp with your copyright.  I should've checked that on your last contribution.

**Comment by coin-au-carre** [comment]
Thank you @HowardHinnant for your answer. If `xdg-user-dir` is not available then the download folder revert back to the old default one. So what is not good is the fact that we still try to launch the command on all non WIN32 platform if I understand correctly ? 
I agree that the compile time and runtime solutions are necessary.

**Comment by HowardHinnant** [comment]
A client can non-intrusively use `xdg-user-dir` if desired and send the result of that to this library via `set_install`, right?

**Comment by coin-au-carre** [comment]
I see your point indeed.

**Comment by HowardHinnant** [comment]
I will try to get `set_install` documented within about 12 hours.  Then your use case with `xdg-user-dir` might make a nice example in the wiki on how to use `set_install`.

**Comment by HowardHinnant** [comment]
`set_install` now documented: https://github.com/HowardHinnant/date/commit/f3b61aab48675dd13663f01aa294fc2e7e451b07

**Comment by coin-au-carre** [comment]
Ok nice ty I will try to add an `xdg-user-dir` example in the wiki

**Comment by HowardHinnant** [comment]
Awesome, love it!

**Pull request closed without merging**
