### PR TITLE
Enhancements to initial travis-ci support

### PR DESCRIPTION
**Pull request by rigtorp**
Added some nice descriptions and clang 6 & 7

### CODE REVIEW

**Comment by rigtorp** [comment]
@HowardHinnant you need to login to travis-ci with github SSO and enable builds for date repo. After you do that the PRs here will be gated by successful build in travis.

**Comment by rigtorp** [comment]
@miketsukerman

**Comment by HowardHinnant** [comment]
@rigtorp  I have just turned on "Build pushed branches" and "Build pushed pull requests".

**Comment by rigtorp** [comment]
👆 Look above 👆 we got nice integration showing us if a PR passes all tests. This is ready to merge.

**Comment by miketsukerman** [comment]
@rigtorp well done. can I ask you to update the readme file and change badge url to 
```
[![Build Status](https://travis-ci.org/HowardHinnant/date.svg?branch=master)](https://travis-ci.org/HowardHinnant/date)
```

**Comment by miketsukerman** [comment]
@rigtorp well done :+1:

**Pull request merged**
